### ISSUE TITLE
Failure to install on OSX/Windows due to dependency

### ISSUE THREAD

**Issue by banesullivan** [conda-forge/vtki-feedstock#1]
Issue:

Please also see comments after  https://github.com/vtkiorg/vtki/issues/127#issuecomment-473733245

Tried creating a dummy conda env to install/test and I'm getting this error:

Mac OS X, Python 3.7

```zsh
(base) ➜ conda create -n foo python=3.7
(base) ➜ conda activate foo
(foo) ➜ conda config --add channels conda-forge
(foo) ➜ conda install vtki
Collecting package metadata: done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - vtki -> libgcc-ng[version='>=7.3.0']

```

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list
# packages in environment at /Users/bane/anaconda3/envs/foo:
#
# Name                    Version                   Build  Channel
ca-certificates           2019.1.23                     0
certifi                   2019.3.9                 py37_0
libcxx                    4.0.1                hcfea43d_1
libcxxabi                 4.0.1                hcfea43d_1
libedit                   3.1.20181209         hb402a30_0
libffi                    3.2.1                h475c297_4
ncurses                   6.1                  h0a44026_1
openssl                   1.1.1b               h1de35cc_1
pip                       19.0.3                   py37_0
python                    3.7.2                haf84260_0
readline                  7.0                  h1de35cc_5
setuptools                40.8.0                   py37_0
sqlite                    3.27.2               ha441bb4_0
tk                        8.6.8                ha441bb4_0
wheel                     0.33.1                   py37_0
xz                        5.2.4                h1de35cc_4
zlib                      1.2.11               h1de35cc_3
```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

     active environment : foo
    active env location : /Users/bane/anaconda3/envs/foo
            shell level : 2
       user config file : /Users/bane/.condarc
 populated config files : /Users/bane/.condarc
          conda version : 4.6.7
    conda-build version : 3.10.5
         python version : 3.6.8.final.0
       base environment : /Users/bane/anaconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/osx-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/bane/anaconda3/pkgs
                          /Users/bane/.conda/pkgs
       envs directories : /Users/bane/anaconda3/envs
                          /Users/bane/.conda/envs
               platform : osx-64
             user-agent : conda/4.6.7 requests/2.18.4 CPython/3.6.8 Darwin/18.2.0 OSX/10.14.3
                UID:GID : 501:20
             netrc file : None
           offline mode : False
```
</details>

**Comment by hadim** [comment]
Ping @conda-forge/help-python. Could you look at this issue?

Do you think removing the C compiler dependency from the recipe is ok? Since we compile nothing during the build (the package is noarch), I guess we don't need a C compiler. That being said the package depends on vtk which is tied to a C compiler...

What are the conda-forge recommendations in this situation?

**Comment by banesullivan** [comment]
Note this is occurring on an AppVeyor CI I set up to test this deployment: https://ci.appveyor.com/project/banesullivan/vtki-deployment-test/history

**Comment by beckermr** [comment]
If you don't have a direct dependence on a package, it should not be in any of the build, host or run sections.

**Comment by marcelotrevisani** [comment]
This recipe cannot be ``noarch``
before you were using a C compiler, and this is not independent of a platform
and you have to install a specific lib for linux platform, so, it is not independent of platform

If you remove the ``yum_requirements`` and you do not rely in any operational systems, that could be ``noarch`` then

**Comment by hadim** [comment]
I see @marcelotrevisani. Thanks for the input.

I will try to remove the yum dep then since it's more a dependency of vtk and not vtki.

**Comment by marcelotrevisani** [comment]
I think your tests will fail if you execute anything related to ``vtk``

But let's try, I might be wrong! :)

**Comment by beckermr** [comment]
> If you don't have a direct dependence on a package, it should not be in any of the build, host or run sections.

Words to live by. ;p

They apply to the yum deps too I think.

**Comment by hadim** [comment]
All green: https://github.com/conda-forge/vtki-feedstock/pull/3

I'll wait for your approbation before I merge this PR.

**Comment by beckermr** [comment]
@marcelotrevisani Looking at the source code, the package itself is pure python. Making it noarch and simply testing an import is sufficient for packaging with conda. Whether or not VTK actually works is a problem for the VTK package. Of course the upstream python package should probably actually test that the code works with vtk. However we are only testing here whether or not the thing got installed in some place that is not crazy.

**Comment by hadim** [comment]
Thanks both for your valuable input!

@banesullivan: please retest the OSX installation once the new package got uploaded and close here if it works.

**Comment by beckermr** [comment]
You might need to wait ~20 minutes for the mirrors to update after the upload completes.

**Comment by banesullivan** [comment]
Working on OS X now! Thanks, everyone!!

Also, the Travis (and AppVeyor whenever it decides to get its stuff together) tests appear to be working and set up to run weekly: https://github.com/vtkiorg/vtki-deployment-test
