### ISSUE TITLE
We've renamed vtki to pyvista

### ISSUE THREAD

**Issue by banesullivan** [conda-forge/vtki-feedstock#14]
Per https://github.com/pyvista/vista/issues/208, we had to rename the software.

@hadim do you know what I should do to address this? Will we have to delete this feed stock and make a new one?

Note the release staged in #13 is a broken release

**Comment by banesullivan** [comment]
Its PyVista `pyvista` actually... currently on PyPI

```bash
pip install pyvista
```

**Comment by banesullivan** [comment]
Ping @conda-forge/help-python. How should I address our recent name change to the software?

**Comment by hadim** [comment]
Sorry, @banesullivan I don't really have time at the moment to look into that. Hopefully, conda forge devs will be able to help you soon!

**Comment by isuruf** [comment]
Somebody needs to create a PR to conda-forge/staged-recipes repo with the contents of `recipe` folder here copied to `recipes/pyvista` and the name also changed in `meta.yaml

**Comment by banesullivan** [comment]
I think I did this in https://github.com/conda-forge/staged-recipes/pull/8394 but I'm having some trouble
